apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonapp

  template:
    metadata:
      labels:
        app: pythonapp


    spec:
      containers:
        - name: pythonapp
          image: hunterzoro/pythonapp:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
